// Module included in the following assemblies:
//
// * networking/using-rfhe.adoc

:_content-type: PROCEDURE
[id="nw-rfhe-creating_bmc_event_sub_{context}"]
= Subscribing to Redfish BMC hardware events for a cluster node

You can configure applications that are running on bare-metal cluster nodes to subscribe to Redfish hardware events that are generated on the baseboard management controller (BMC). Example Redfish events include increase in device temperature, or removal of a device. Redfish hardware events are delivered to subscribed applications using a Redfish events REST API.

Before you can subscribe to Redfish hardware events for the node, you must create a `BMCEventSubscription` custom resource (CR) for the node.

[IMPORTANT]
====
You can only create a `BMCEventSubscription` CR for physical hardware that supports Redfish and has a vendor interface set to `redfish` or `idrac-redfish`.
====

[NOTE]
====
Use the `BMCEventSubscription` CR to subscribe to pre-defined Redfish events. The Redfish standard does not provide an option to create specific alerts and thresholds. For example, to receive an alert event when an enclosure's temperature exceeds 40° Celsius, you need to manually configure the event according to the vendor's recommendations.
====

.Prerequisites

* Install the OpenShift CLI (`oc`).
* Log in as a user with `cluster-admin` privileges.
* Deploy a bare-metal node with Redfish hardware in your cluster.
* Get the user name and password for the bare-metal node BMC.

.Procedure

. Cordon and drain the node:
+
[source,terminal]
----
$ oc adm cordon <node_name>
----
+
where:
+
--
<node_name>:: is the bare-metal node that is generating Redfish hardware events.
--
+
.Example output
[source,terminal]
----
node/compute-1.example.com cordoned
----
+
[source,terminal]
----
$ oc adm drain <node_name> --force=true
----

. Shut down the node:
+
[source,terminal]
----
$ do oc debug node/<node_name> -- chroot /host shutdown -h 1
----

. Confirm the hardware has the Redfish `EventService` enabled using the following `curl` command:
+
[source,terminal]
----
curl https://<bmc_address>/redfish/v1/EventService --insecure -H 'Content-Type: application/json' -u "<user_name>:<password>"
----
+
where:
+
--
bmc_address:: is the DRAC IP address of the BMC controller
user_name:: is the BMC user login
password:: is the BMC password login
--
+
.Example output
[source,terminal]
----
{
   "@odata.context":"/redfish/v1/$metadata#EventService.EventService",
   "@odata.id":"/redfish/v1/EventService",
   "@odata.type":"#EventService.v1_0_2.EventService",
   "Actions":{
      "#EventService.SubmitTestEvent":{
         "EventType@Redfish.AllowableValues":[
            "StatusChange",
            "ResourceUpdated",
            "ResourceAdded",
            "ResourceRemoved",
            "Alert"
         ],
         "target":"/redfish/v1/EventService/Actions/EventService.SubmitTestEvent"
      }
   },
   "DeliveryRetryAttempts":3,
   "DeliveryRetryIntervalSeconds":30,
   "Description":"Event Service represents the properties for the service",
   "EventTypesForSubscription":[
      "StatusChange",
      "ResourceUpdated",
      "ResourceAdded",
      "ResourceRemoved",
      "Alert"
   ],
   "EventTypesForSubscription@odata.count":5,
   "Id":"EventService",
   "Name":"Event Service",
   "ServiceEnabled":true,
   "Status":{
      "Health":"OK",
      "HealthRollup":"OK",
      "State":"Enabled"
   },
   "Subscriptions":{
      "@odata.id":"/redfish/v1/EventService/Subscriptions"
   }
}
----

. Create a `BMCEventSubscription` resource to subscribe to the Redfish events:

.. Save the following YAML in the `bmc_sub.yaml` file:
+
[source,yaml]
----
apiVersion: metal3.io/v1alpha1
kind: BMCEventSubscription
metadata:
  name: sub-01
  namespace: openshift-machine-api
spec:
   hostName: <hostname> <1>
   destination: https://hw-event-proxy-cloud-native-events.apps.compute-1.example.com/webhook <2>
   context: ''
----
<1> Specifies the name or UUID of the worker node where the Redfish events are generated.
<2> Specifies the Baremetal Hardware Event proxy service.
+
.. Create the `BMCEventSubscription` CR:
+
[source,yaml]
----
$ oc create -f bmc_sub.yaml
----
+
.Example output
[source,json]
----
{
   "ServiceEnabled":true,
   "Status":{
      "Health":"OK",
      "HealthRollup":"OK",
      "State":"Enabled"
   }
}
----
